name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends $(cat deps/ubuntu-24.04.txt)

      - name: Check formatting
        run: clang-format-20 --dry-run --Werror $(git ls-files '*.cpp' '*.hpp')

      - name: Cache userver sources and ccache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/CPM
            ~/.cache/ccache
          key: build-${{ hashFiles('CMakeLists.txt', 'deps/ubuntu-24.04.txt') }}-${{ github.run_number }}
          restore-keys: |
            build-${{ hashFiles('CMakeLists.txt', 'deps/ubuntu-24.04.txt') }}-
            build-

      - name: Build (with clang-tidy)
        run: |
          ccache -M 2G
          cmake --preset debug
          cmake --build --preset debug
          ccache -s

      - name: Run unit tests
        run: ctest --preset debug

      # TODO deploy to Heroku

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"